services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${CLIMBDESK_RABBITMQ_USERNAME:-climbdesk}
      RABBITMQ_DEFAULT_PASS: ${CLIMBDESK_RABBITMQ_PASSWORD:-climbdesk}
      RABBITMQ_DEFAULT_VHOST: ${CLIMBDESK_RABBITMQ_VIRTUAL_HOST:-/}
    ports:
      - "${CLIMBDESK_RABBITMQ_PORT:-5672}:5672"
      - "${CLIMBDESK_RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
