create table admin_users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  role varchar(20) not null,
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint uk_admin_users_email unique (email),
  constraint ck_admin_users_role check (role in ('MANAGER', 'STAFF')),
  constraint ck_admin_users_status check (status in ('ACTIVE', 'INACTIVE'))
);

create table members (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  phone varchar(30) not null,
  email varchar(255),
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deactivated_at timestamptz,
  constraint uk_members_phone unique (phone),
  constraint ck_members_status check (status in ('ACTIVE', 'INACTIVE')),
  constraint ck_members_deactivated_at check (
    (status = 'INACTIVE' and deactivated_at is not null)
    or (status = 'ACTIVE')
  )
);

create table pass_products (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  type varchar(30) not null,
  total_count integer not null,
  price numeric(12,0),
  valid_days integer,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint ck_pass_products_type check (type in ('COUNT_PASS')),
  constraint ck_pass_products_total_count check (total_count >= 1),
  constraint ck_pass_products_price check (price is null or price >= 0),
  constraint ck_pass_products_valid_days check (valid_days is null or valid_days >= 1)
);

create table class_sessions (
  id bigint generated by default as identity primary key,
  title varchar(150) not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  capacity integer not null,
  reserved_count integer not null,
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  canceled_at timestamptz,
  cancel_reason varchar(500),
  affected_reservation_count integer not null default 0,
  constraint ck_class_sessions_status check (status in ('OPEN', 'CLOSED', 'CANCELED')),
  constraint ck_class_sessions_time_range check (starts_at < ends_at),
  constraint ck_class_sessions_capacity check (capacity >= 1),
  constraint ck_class_sessions_reserved_count check (reserved_count >= 0 and reserved_count <= capacity),
  constraint ck_class_sessions_affected_reservation_count check (affected_reservation_count >= 0),
  constraint ck_class_sessions_cancel_fields check (
    (status = 'CANCELED' and canceled_at is not null)
    or (status <> 'CANCELED')
  )
);

create table member_passes (
  id bigint generated by default as identity primary key,
  member_id bigint not null,
  pass_product_id bigint not null,
  product_name_snapshot varchar(100) not null,
  pass_type_snapshot varchar(30) not null,
  total_count integer not null,
  remaining_count integer not null,
  price_snapshot numeric(12,0),
  valid_days_snapshot integer,
  status varchar(20) not null,
  issued_at timestamptz not null,
  expires_at timestamptz,
  version bigint not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint fk_member_passes_member foreign key (member_id) references members (id) on delete restrict,
  constraint fk_member_passes_pass_product foreign key (pass_product_id) references pass_products (id) on delete restrict,
  constraint ck_member_passes_status check (status in ('ACTIVE', 'EXHAUSTED', 'EXPIRED', 'CANCELED')),
  constraint ck_member_passes_count_range check (
    total_count >= 1 and remaining_count >= 0 and remaining_count <= total_count
  ),
  constraint ck_member_passes_version check (version >= 0),
  constraint ck_member_passes_valid_days_snapshot check (valid_days_snapshot is null or valid_days_snapshot >= 1),
  constraint ck_member_passes_expires_after_issued check (expires_at is null or expires_at > issued_at)
);

create table reservations (
  id bigint generated by default as identity primary key,
  member_id bigint not null,
  class_session_id bigint not null,
  member_pass_id bigint not null,
  status varchar(20) not null,
  reserved_at timestamptz not null,
  canceled_at timestamptz,
  cancel_reason varchar(40),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint fk_reservations_member foreign key (member_id) references members (id) on delete restrict,
  constraint fk_reservations_class_session foreign key (class_session_id) references class_sessions (id) on delete restrict,
  constraint fk_reservations_member_pass foreign key (member_pass_id) references member_passes (id) on delete restrict,
  constraint ck_reservations_status check (status in ('CONFIRMED', 'CANCELED')),
  constraint ck_reservations_cancel_reason check (
    cancel_reason is null or cancel_reason in ('USER_REQUESTED', 'CLASS_SESSION_CANCELED')
  ),
  constraint ck_reservations_cancel_fields check (
    (status = 'CONFIRMED' and canceled_at is null and cancel_reason is null)
    or (status = 'CANCELED' and canceled_at is not null and cancel_reason is not null)
  )
);

create table pass_usage_histories (
  id bigint generated by default as identity primary key,
  member_pass_id bigint not null,
  reservation_id bigint not null,
  type varchar(20) not null,
  reason varchar(40) not null,
  changed_count integer not null,
  remaining_count_after integer not null,
  created_at timestamptz not null,
  constraint fk_pass_usage_histories_member_pass foreign key (member_pass_id) references member_passes (id) on delete restrict,
  constraint fk_pass_usage_histories_reservation foreign key (reservation_id) references reservations (id) on delete restrict,
  constraint ck_pass_usage_histories_type check (type in ('CONSUME', 'RESTORE')),
  constraint ck_pass_usage_histories_reason check (
    reason in ('RESERVATION_CONFIRMED', 'RESERVATION_CANCELED', 'CLASS_SESSION_CANCELED')
  ),
  constraint ck_pass_usage_histories_changed_count check (
    (type = 'CONSUME' and changed_count = -1)
    or (type = 'RESTORE' and changed_count = 1)
  ),
  constraint ck_pass_usage_histories_remaining_count_after check (remaining_count_after >= 0)
);

create table outbox_events (
  id bigint generated by default as identity primary key,
  event_type varchar(100) not null,
  aggregate_type varchar(100) not null,
  aggregate_id bigint not null,
  payload jsonb not null,
  status varchar(20) not null,
  retry_count integer not null,
  occurred_at timestamptz not null,
  published_at timestamptz,
  next_retry_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint ck_outbox_events_status check (status in ('PENDING', 'PUBLISHED', 'FAILED')),
  constraint ck_outbox_events_retry_count check (retry_count >= 0),
  constraint ck_outbox_events_published_at check (
    (status = 'PUBLISHED' and published_at is not null)
    or (status <> 'PUBLISHED')
  )
);

create index idx_admin_users_status_role
  on admin_users (status, role);

create index idx_members_created_at_id
  on members (created_at desc, id desc);

create index idx_members_status
  on members (status);

create index idx_pass_products_created_at_id
  on pass_products (created_at desc, id desc);

create index idx_class_sessions_starts_at_id
  on class_sessions (starts_at desc, id desc);

create index idx_class_sessions_status_starts_at
  on class_sessions (status, starts_at);

create index idx_member_passes_member_id
  on member_passes (member_id);

create index idx_member_passes_member_status
  on member_passes (member_id, status);

create index idx_member_passes_available_selection
  on member_passes (member_id, status, expires_at asc nulls last, issued_at asc, id asc)
  where status = 'ACTIVE' and remaining_count > 0;

create unique index uk_reservations_confirmed_member_class
  on reservations (member_id, class_session_id)
  where status = 'CONFIRMED';

create index idx_reservations_member_reserved_at
  on reservations (member_id, reserved_at desc, id desc);

create index idx_reservations_class_session_status
  on reservations (class_session_id, status);

create index idx_reservations_member_pass_id
  on reservations (member_pass_id);

create index idx_reservations_status_reserved_at
  on reservations (status, reserved_at desc);

create index idx_pass_usage_histories_member_pass_created_at
  on pass_usage_histories (member_pass_id, created_at desc, id desc);

create index idx_pass_usage_histories_reservation_id
  on pass_usage_histories (reservation_id);

create index idx_outbox_events_pending
  on outbox_events (status, next_retry_at asc nulls first, id asc)
  where status in ('PENDING', 'FAILED');

create index idx_outbox_events_aggregate
  on outbox_events (aggregate_type, aggregate_id);

create index idx_outbox_events_occurred_at
  on outbox_events (occurred_at desc, id desc);
