alter table outbox_events
  add column publish_target varchar(30) not null default 'NONE',
  add column schema_version integer not null default 1,
  add column last_error varchar(1000),
  add constraint ck_outbox_events_publish_target
    check (publish_target in ('NONE', 'RABBITMQ')),
  add constraint ck_outbox_events_schema_version
    check (schema_version >= 1);

create index idx_outbox_events_publishable
  on outbox_events (status, next_retry_at asc nulls first, id asc)
  where publish_target = 'RABBITMQ'
    and status in ('PENDING', 'FAILED');

create table processed_events (
  consumer_name varchar(100) not null,
  event_id bigint not null,
  event_type varchar(100) not null,
  processed_at timestamptz not null,
  primary key (consumer_name, event_id)
);

create table reservation_notification_requests (
  id bigint generated by default as identity primary key,
  source_event_id bigint not null,
  reservation_id bigint not null,
  member_id bigint not null,
  notification_type varchar(40) not null,
  status varchar(30) not null,
  created_at timestamptz not null,
  constraint uk_reservation_notification_source_event unique (source_event_id),
  constraint ck_reservation_notification_type
    check (notification_type in ('RESERVATION_CONFIRMED')),
  constraint ck_reservation_notification_status
    check (status in ('READY', 'SKIPPED_STALE'))
);
